apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: bl4yuo5jg-nodejs 
  janus-idp.io/tekton: bl4yuo5jg-nodejs
  backstage.io/kubernetes-id: bl4yuo5jg-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: bl4yuo5jg-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml